### ISSUE TITLE
What happend to WolframAlpha MoreSteps?

### ISSUE THREAD

**Issue by GaroleAtharva** [shiftinv/shiftinv#3]
Could you please bring back the extension, was really helpful

**Comment by shiftinv** [comment]
I removed it due to a variety of reasons, including but not limited to personal reasons. I know this doesn't help particularly, but I have no plans to bring it back; I wouldn't have the time to continue maintaining it as it stands right now, anyway.

**Comment by GaroleAtharva** [comment]
Could you atleast share the source code, so that I can work on it on my own
.

**Comment by shiftinv** [comment]
No, sorry. I'm not going to go into detailed reasons, it was mostly (but not entirely) my own decision. I never expected it to achieve any popularity; you might be able to find it in other places/archives (that I'm not responsible for).
